### GET specific set information from API
GET http://localhost:3001/api/sets/6210-1  HTTP/1.1

### GET all users
GET http://localhost:3001/api/users HTTP/1.1

### GET one specific user
GET http://localhost:3001/api/users/Marie HTTP/1.1

### POST a new user
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json 

{
    "name": "Anke"  
}

### PATCH a new set to a user
PATCH http://localhost:3001/api/users/Marie HTTP/1.1
Content-Type: application/json

{ 
"numberSet":"11001-1"
}

### DELETE a set from a user
DELETE http://localhost:3001/api/users/Marie/sets/11001-1 HTTP/1.1